Zend/zend_atomic.h: fix build for upcoming `gcc-14`
In gcc.gnu.org/PR60512 `gcc-14` implemented `c_atomic` feature and
exposed build failure on `php` as:

    /build/php-8.2.13/Zend/zend_atomic.h: In function 'zend_atomic_bool_store_ex':
    /build/php-8.2.13/Zend/zend_atomic.h:96:9: warning: implicit declaration of function '__c11_atomic_store'; did you mean '__atomic_store'? [-Wimplicit-function-declaration]
       96 |         __c11_atomic_store(&obj->value, desired, __ATOMIC_SEQ_CST);
          |         ^~~~~~~~~~~~~~~~~~
          |         __atomic_store
    ...
    ld: /build/php-8.2.13/Zend/zend_atomic.h:96:(.text+0x1301): undefined reference to `__c11_atomic_store'
    ld: /build/php-8.2.13/Zend/zend_atomic.h:96:(.text+0x1e49): undefined reference to `__c11_atomic_store'

As I understand the build failure happens because `php` uses `clang`'s
internal functions prefixed with `__c11_*` that implement atomics instead
of standard-defined `atomic_*` ones. `gcc` implements ony standard-defined
ones.

The change fixes build for me.