Fix -Wdefault-const-init-field-unsafe with clang 21 (#21135)
Fixes the following warning:

Zend/zend_alloc.c:3469:18: error: default initialization of an object of type 'zend_mm_storage' (aka 'struct _zend_mm_storage') with const member leaves the object uninitialized [-Werror,-Wdefault-const-init-field-unsafe]
 3469 |         zend_mm_storage tmp_storage, *storage;
      |                         ^
Zend/zend_alloc.h:313:25: note: member 'handlers' declared 'const' here
  313 |         const zend_mm_handlers handlers;
      |                                ^

(cherry picked from commit 68a10628a2d6ed7d58bbe4e6dd670bee5c348233)