apply https://github.com/BLAKE3-team/BLAKE3/pull/443
caused
```
/Users/runner/work/php-src/php-src/ext/hash/blake3/upstream_blake3/c/blake3_dispatch.c:237:26: error: unused variable 'features' [-Werror,-Wunused-variable]
  const enum cpu_feature features = get_cpu_features();
```
on 32bit x86-32 linux builds.